[palettes.theme]
blue = "#7daea3"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
cyan = "#89b482"
magenta = "#d3869b"
white = "#d4be98"
black = "#3c3836"
rosewater = "#d8a657"
flamingo = "#ea6962"
pink = "#d3869b"
mauve = "#7daea3"
maroon = "#ea6962"
peach = "#d8a657"
teal = "#89b482"
sky = "#7daea3"
sapphire = "#7daea3"
lavender = "#83a598"
text = "#d4be98"
subtext1 = "#bdae93"
subtext0 = "#928374"
overlay2 = "#928374"
overlay1 = "#504945"
overlay0 = "#504945"
surface2 = "#504945"
surface1 = "#3c3836"
surface0 = "#32302f"
base = "#282828"
mantle = "#1d2021"
crust = "#1d2021"
